-- Generated by `knowledge`. Do not edit by hand.
-- The database itself is gitignored; this file is the tracked artifact.
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
INSERT INTO spec (id, title, path, status, confidence, ontology_version, md_hash, ttl_hash, modeled_md_hash, modeled_ttl_hash, modeled_at, modeled_by, verified_at, verified_by, verified_against_commit, demoted_at, demoted_reason, publishes_to_wiki, wiki_page, created_at, updated_at) VALUES ('example', 'Example', 'specs/example', 'draft', NULL, NULL, '298e8af21fa097d679feb6bc8d41053286c383d6fc905846c8ee8c13fe172efa', '39cec9cf385ac402298ab97d3aa29e3b85b7626a6c00ed02ee53619a266a3d35', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'Example', '2026-08-26T17:29:32Z', '2026-08-26T17:29:32Z');
INSERT INTO spec_event (id, spec_id, event, actor, at, detail) VALUES (1, 'example', 'created', 'scan', '2026-08-26T17:29:32Z', NULL);
COMMIT;
PRAGMA foreign_keys=ON;
