"""SQLite metadata, dumped to git-tracked SQL.

The database file is a build product; dump.sql is what git tracks, so a diff is readable
and a merge conflict lands in SQL rather than in a binary. The dump is written with an
explicit ORDER BY on every table so two dumps of the same data are byte-identical.
"""

from __future__ import annotations

import os
import sqlite3
import time
from datetime import UTC, datetime
from pathlib import Path

from knowledge.paths import Paths

TABLES = ("spec", "spec_dependency", "spec_resource", "open_question", "spec_event")

SCHEMA = """
CREATE TABLE IF NOT EXISTS spec (
  id                      TEXT PRIMARY KEY,
  title                   TEXT NOT NULL,
  path                    TEXT NOT NULL,
  status                  TEXT NOT NULL CHECK (status IN ('draft','verified')),
  confidence              TEXT CHECK (confidence IN ('low','medium','high')),
  ontology_version        TEXT,
  md_hash                 TEXT,
  ttl_hash                TEXT,
  modeled_md_hash         TEXT,
  modeled_ttl_hash        TEXT,
  modeled_at              TEXT,
  modeled_by              TEXT,
  verified_at             TEXT,
  verified_by             TEXT,
  verified_against_commit TEXT,
  demoted_at              TEXT,
  demoted_reason          TEXT,
  publishes_to_wiki       INTEGER NOT NULL DEFAULT 1,
  wiki_page               TEXT,
  created_at              TEXT NOT NULL,
  updated_at              TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS spec_dependency (
  spec_id TEXT NOT NULL REFERENCES spec(id) ON DELETE CASCADE,
  glob    TEXT NOT NULL,
  note    TEXT,
  PRIMARY KEY (spec_id, glob)
);

CREATE TABLE IF NOT EXISTS spec_resource (
  spec_id TEXT NOT NULL REFERENCES spec(id) ON DELETE CASCADE,
  path    TEXT NOT NULL,
  kind    TEXT,
  note    TEXT,
  PRIMARY KEY (spec_id, path)
);

CREATE TABLE IF NOT EXISTS open_question (
  id          INTEGER PRIMARY KEY,
  spec_id     TEXT NOT NULL REFERENCES spec(id) ON DELETE CASCADE,
  claim_iri   TEXT,
  question    TEXT NOT NULL,
  asked_by    TEXT NOT NULL,
  asked_at    TEXT NOT NULL,
  status      TEXT NOT NULL CHECK (status IN ('open','answered','dropped')),
  answer      TEXT,
  answered_at TEXT
);

CREATE TABLE IF NOT EXISTS spec_event (
  id      INTEGER PRIMARY KEY,
  spec_id TEXT NOT NULL,
  event   TEXT NOT NULL,
  actor   TEXT,
  at      TEXT NOT NULL,
  detail  TEXT
);
"""


def now() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def connect(paths: Paths) -> sqlite3.Connection:
    """Open (or bootstrap) the local database.

    A pulled dump.sql that is newer than the local knowledge.db means someone else — a CI
    job's commit, a teammate's push — moved the tracked state forward since this database
    was last built. Without reloading, the next `db.save` from this stale database would
    rewrite dump.sql back to the old state, silently reverting the pull. Comparing mtimes
    catches that: whichever file was written most recently wins.
    """
    paths.metadata.mkdir(parents=True, exist_ok=True)
    fresh = not paths.db.exists()
    stale = (
        not fresh
        and paths.dump.is_file()
        and paths.dump.stat().st_mtime > paths.db.stat().st_mtime
    )
    conn = sqlite3.connect(paths.db)
    conn.execute("PRAGMA foreign_keys = ON")
    conn.executescript(SCHEMA)
    if fresh and paths.dump.is_file():
        conn.executescript(paths.dump.read_text(encoding="utf-8"))
        conn.execute("PRAGMA foreign_keys = ON")
    elif stale:
        print("dump.sql is newer than knowledge.db — reloading the database from the dump")
        conn.execute("PRAGMA foreign_keys = OFF")
        for table in TABLES:
            conn.execute(f"DELETE FROM {table}")
        conn.executescript(paths.dump.read_text(encoding="utf-8"))
        conn.execute("PRAGMA foreign_keys = ON")
    conn.commit()
    return conn


def _literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    return "'" + text.replace("'", "''") + "'"


def dump(conn: sqlite3.Connection, path: Path) -> None:
    lines = [
        "-- Generated by `knowledge`. Do not edit by hand.",
        "-- The database itself is gitignored; this file is the tracked artifact.",
        "PRAGMA foreign_keys=OFF;",
        "BEGIN TRANSACTION;",
    ]
    for table in TABLES:
        columns = [row[1] for row in conn.execute(f"PRAGMA table_info({table})")]
        order = ", ".join(columns)
        names = ", ".join(columns)
        for row in conn.execute(f"SELECT {names} FROM {table} ORDER BY {order}"):
            values = ", ".join(_literal(value) for value in row)
            lines.append(f"INSERT INTO {table} ({names}) VALUES ({values});")
    lines.append("COMMIT;")
    lines.append("PRAGMA foreign_keys=ON;")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def save(conn: sqlite3.Connection, paths: Paths) -> None:
    conn.commit()
    dump(conn, paths.dump)
    # `connect` reloads whenever dump.sql is newer than knowledge.db, to pick up a pulled
    # dump the local database doesn't know about yet. Writing the dump necessarily happens
    # after the commit above, so without this the dump would *always* look newer than the
    # database it was just derived from, and every subsequent `connect` would "reload" from
    # a dump that is in fact identical to what's already there. Stamping both files to the
    # same mtime keeps the comparison meaningful: only a dump written by someone else, with
    # no matching local commit, ends up strictly newer.
    now = time.time()
    os.utime(paths.dump, (now, now))
    os.utime(paths.db, (now, now))


def record_event(
    conn: sqlite3.Connection,
    spec_id: str,
    event: str,
    actor: str | None = None,
    detail: str | None = None,
) -> None:
    conn.execute(
        "INSERT INTO spec_event (spec_id, event, actor, at, detail) VALUES (?,?,?,?,?)",
        (spec_id, event, actor, now(), detail),
    )
